name: stretched_mesh_env
channels:
  - conda-forge
dependencies:
  - python =3.12

  - aeolus
  - black
  - cartopy
  - cf-units
  - cftime
  - click
  - cmcrameri
  - cmocean
  - dask
  - esmpy
  - ffmpeg
  - geovista
  - imageio
  - imageio-ffmpeg
  - ipykernel
  - ipython
  - ipywidgets
  - iris >=3.9
  - iris-esmf-regrid >=0.9
  - isort
  - matplotlib >=3.8
  - meshio
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pyvista
  - pip
  - python-stratify
  - ruff
  - scipy
  - trame
  - tqdm

# PyPI
  - pip:
    - swiftascmaps
